namespace: logging
createNamespace: true

replicaCount: 1

image:
  repository: grafana/loki
  pullPolicy: IfNotPresent
  tag: "2.9.8"

service:
  type: ClusterIP
  port: 3100

resources: {}

persistence:
  enabled: true
  size: 10Gi
  # Optional; set to your StorageClass name, or omit for cluster default
  # storageClassName: standard

nodeSelector: {}
tolerations: []
affinity: {}
